---@meta

---@class USupraAnimBlueprint_C : UAnimInstance
---@field UberGraphFrame FPointerToUberGraphFrame
---@field AnimGraphNode_UseCachedPose_24 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_23 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_11 FAnimNode_SaveCachedPose
---@field AnimGraphNode_ModifyBone_4 FAnimNode_ModifyBone
---@field AnimGraphNode_LocalToComponentSpace_1 FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_ModifyBone_3 FAnimNode_ModifyBone
---@field AnimGraphNode_UseCachedPose_22 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_21 FAnimNode_UseCachedPose
---@field AnimGraphNode_LayeredBoneBlend_9 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_LayeredBoneBlend_8 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_20 FAnimNode_UseCachedPose
---@field AnimGraphNode_LayeredBoneBlend_7 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_TwoWayBlend_11 FAnimNode_TwoWayBlend
---@field AnimGraphNode_TwoWayBlend_10 FAnimNode_TwoWayBlend
---@field AnimGraphNode_SaveCachedPose_10 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_19 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_18 FAnimNode_UseCachedPose
---@field AnimGraphNode_ApplyAdditive FAnimNode_ApplyAdditive
---@field AnimGraphNode_SequencePlayer_14 FAnimNode_SequencePlayer
---@field AnimGraphNode_SaveCachedPose_9 FAnimNode_SaveCachedPose
---@field AnimGraphNode_ComponentToLocalSpace_1 FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_ModifyBone_2 FAnimNode_ModifyBone
---@field AnimGraphNode_LocalToComponentSpace FAnimNode_ConvertLocalToComponentSpace
---@field AnimGraphNode_UseCachedPose_17 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_16 FAnimNode_UseCachedPose
---@field AnimGraphNode_TransitionResult_11 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_10 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_9 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_8 FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_13 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_12 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_9 FAnimNode_TwoWayBlend
---@field AnimGraphNode_StateResult_8 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_11 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_10 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_8 FAnimNode_TwoWayBlend
---@field AnimGraphNode_StateResult_7 FAnimNode_StateResult
---@field AnimGraphNode_UseCachedPose_15 FAnimNode_UseCachedPose
---@field AnimGraphNode_StateResult_6 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_9 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer_8 FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_7 FAnimNode_TwoWayBlend
---@field AnimGraphNode_StateResult_5 FAnimNode_StateResult
---@field AnimGraphNode_StateMachine_1 FAnimNode_StateMachine
---@field AnimGraphNode_SaveCachedPose_8 FAnimNode_SaveCachedPose
---@field AnimGraphNode_ModifyBone_1 FAnimNode_ModifyBone
---@field AnimGraphNode_SaveCachedPose_7 FAnimNode_SaveCachedPose
---@field AnimGraphNode_BlendSpacePlayer_2 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_TwoWayBlend_6 FAnimNode_TwoWayBlend
---@field AnimGraphNode_Slot_3 FAnimNode_Slot
---@field AnimGraphNode_SequencePlayer_7 FAnimNode_SequencePlayer
---@field AnimGraphNode_UseCachedPose_14 FAnimNode_UseCachedPose
---@field AnimGraphNode_ModifyBone FAnimNode_ModifyBone
---@field AnimGraphNode_UseCachedPose_13 FAnimNode_UseCachedPose
---@field AnimGraphNode_TwoWayBlend_5 FAnimNode_TwoWayBlend
---@field AnimGraphNode_LayeredBoneBlend_6 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_12 FAnimNode_UseCachedPose
---@field AnimGraphNode_LayeredBoneBlend_5 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SequencePlayer_6 FAnimNode_SequencePlayer
---@field AnimGraphNode_Slot_2 FAnimNode_Slot
---@field AnimGraphNode_TransitionResult_7 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_6 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_5 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_4 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_3 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_2 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult_1 FAnimNode_TransitionResult
---@field AnimGraphNode_TransitionResult FAnimNode_TransitionResult
---@field AnimGraphNode_SequencePlayer_5 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_4 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_4 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_3 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_3 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_2 FAnimNode_StateResult
---@field AnimGraphNode_SequencePlayer_2 FAnimNode_SequencePlayer
---@field AnimGraphNode_StateResult_1 FAnimNode_StateResult
---@field AnimGraphNode_BlendSpacePlayer_1 FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_LayeredBoneBlend_4 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_BlendSpacePlayer FAnimNode_BlendSpacePlayer
---@field AnimGraphNode_StateResult FAnimNode_StateResult
---@field AnimGraphNode_StateMachine FAnimNode_StateMachine
---@field AnimGraphNode_Root FAnimNode_Root
---@field AnimGraphNode_TwoWayBlend_4 FAnimNode_TwoWayBlend
---@field AnimGraphNode_UseCachedPose_11 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_6 FAnimNode_SaveCachedPose
---@field AnimGraphNode_LayeredBoneBlend_3 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_TwoWayBlend_3 FAnimNode_TwoWayBlend
---@field AnimGraphNode_LayeredBoneBlend_2 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_SaveCachedPose_5 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_10 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_4 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_9 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_8 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_7 FAnimNode_UseCachedPose
---@field AnimGraphNode_ComponentToLocalSpace FAnimNode_ConvertComponentToLocalSpace
---@field AnimGraphNode_SequencePlayer_1 FAnimNode_SequencePlayer
---@field AnimGraphNode_SequencePlayer FAnimNode_SequencePlayer
---@field AnimGraphNode_TwoWayBlend_2 FAnimNode_TwoWayBlend
---@field AnimGraphNode_SaveCachedPose_3 FAnimNode_SaveCachedPose
---@field AnimGraphNode_TwoWayBlend_1 FAnimNode_TwoWayBlend
---@field AnimGraphNode_LayeredBoneBlend_1 FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_UseCachedPose_6 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_5 FAnimNode_UseCachedPose
---@field AnimGraphNode_Slot_1 FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose_2 FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_4 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_3 FAnimNode_UseCachedPose
---@field AnimGraphNode_SaveCachedPose_1 FAnimNode_SaveCachedPose
---@field AnimGraphNode_TwoWayBlend FAnimNode_TwoWayBlend
---@field AnimGraphNode_LayeredBoneBlend FAnimNode_LayeredBoneBlend
---@field AnimGraphNode_Slot FAnimNode_Slot
---@field AnimGraphNode_SaveCachedPose FAnimNode_SaveCachedPose
---@field AnimGraphNode_UseCachedPose_2 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose_1 FAnimNode_UseCachedPose
---@field AnimGraphNode_UseCachedPose FAnimNode_UseCachedPose
---@field Speed_Forward float
---@field Speed_Strafe float
---@field Speed float
---@field ['IsSwimming?'] boolean
---@field ['Is In Air?'] boolean
---@field Health float
---@field IsPlayer boolean
---@field IsPunching boolean
---@field isShooting boolean
---@field IsHoldingGun boolean
---@field ['Head Rotation'] FRotator
---@field ['Local Self'] AActor
---@field Player AFirstPersonCharacter_C
---@field ['Head Rotation Talk'] FRotator
---@field IsPointing boolean
---@field IsThreatening boolean
---@field GunArmRotation FRotator
---@field SwordArmRotation FRotator
---@field IsHoldingSword boolean
---@field RunningStyle BlendspaceSelection::Type
---@field RandomPunch int32
---@field swordanimationplaying boolean
---@field OverrideAnimationAlpha float
---@field SwordArmUseSlotAlpha float
---@field GunArmUseSlotAlpha float
---@field GunArmRotationOverrideMin float
---@field GunArmRotationOverrideMax float
---@field GunArmBackAlpha float
---@field SwordArmRotationOverrideMin float
---@field SwordArmRotationOverrideMax float
---@field WeaponArmSwitchSpeed float
---@field ['IsStandingInWater?'] boolean
---@field bLandedOnSponge boolean
---@field bLandedOnWetSponge boolean
---@field Landed boolean
---@field SwordArmRotateAlpha float
---@field ControllerPitch float
---@field bRedGuyUpdatePlayerArmAlphas boolean
---@field bPreventGunBobbing boolean
---@field ['Game Settings'] UBP_GameSettings_C
---@field bClapping boolean
---@field bClappingIsFast boolean
---@field ClappingPlayRate float
---@field bIsNotClapping_State boolean
---@field bUseClapSound boolean
---@field CustomPose UAnimSequenceBase
---@field CurrentPose UAnimSequenceBase
---@field PoseOverrideAlpha float
---@field bUseCustomPose boolean
---@field bCustomPoseOnlyUpperBody boolean
---@field InstantPoseOverride boolean
---@field bIsCarryingSomething boolean
---@field RecoilingAlpha float
---@field RightHandIK_World FVector
---@field DefaultSlot_ForceFullBody boolean
---@field HoldingGunAlpha float
---@field HoldingGunChangeSpeed float
---@field HoldingSwordAlpha float
---@field HoldingSwordChangeSpeed float
---@field UpperBodySlotAlpha float
---@field bSwingingForward boolean
---@field PointingUpDown float
---@field PointingAlpha float
---@field bCharacterIsVisible boolean
---@field AquaticComponent UBP_AquaticBuoyancy_C
---@field bCharacterIsStatic boolean
local USupraAnimBlueprint_C = {}

---@param AnimGraph FPoseLink
function USupraAnimBlueprint_C:AnimGraph(AnimGraph) end
---@param Asset UAnimSequenceBase
---@param Delay float
---@param BlendInTime float
---@param BlendOutTime float
---@param InPlayRate float
---@param DefaultSlot_ForceFullBody boolean
---@param TimeBeforeComplete float
function USupraAnimBlueprint_C:PlayAnimation_DefaultSlot(Asset, Delay, BlendInTime, BlendOutTime, InPlayRate, DefaultSlot_ForceFullBody, TimeBeforeComplete) end
---@param CurrentFloor FFindFloorResult
---@param PhysicsMaterial UPhysicalMaterial
---@param Actor AActor
---@param Component UPrimitiveComponent
function USupraAnimBlueprint_C:GetCharacterFloor(CurrentFloor, PhysicsMaterial, Actor, Component) end
---@param SkeletalMesh USkeletalMeshComponent
function USupraAnimBlueprint_C:GetSkeletalMesh(SkeletalMesh) end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TransitionResult_4A81BC084F7EB75AC6C9B59DF5AFBBDF() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TransitionResult_A27ECAFE407593E9AA9E299DDF53B174() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TransitionResult_2ED5E5E24DA67530EC83DAB2DFAE6325() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TransitionResult_0EF52E3441DDCDE6A0564497187DCBA8() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TwoWayBlend_F636D5A945E7FA8350BCC18458C4BDE5() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TwoWayBlend_7C368315400712E04681CC85E12E0CC4() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TwoWayBlend_009E65A942F38ACB3E2E9F9BE78B7A79() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TwoWayBlend_230BA8D84C70F2DC50BC5DA3DF0B5026() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TwoWayBlend_FC0C0362490C1F9F9503BCB6CF804757() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TwoWayBlend_8A0E6669498824F3FAA4DEB2BD482EE5() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_ModifyBone_F474B81D4920CF90A7F27E98A308146E() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_ApplyAdditive_ADF63638488F9513FBA639BF7C844EB0() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TwoWayBlend_B2A3E0F142457BDF1EFF80B9461020CC() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_LayeredBoneBlend_333AD598495C839704389EB59AC26957() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_BlendSpacePlayer_A49B1B844DBC3870E57EDBBD574A7ED0() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_LayeredBoneBlend_BD9EDBDB48157BDE667F5C8AE8873DA8() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_BlendSpacePlayer_C6A24E18499A40119312F584F728002F() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TransitionResult_047AC0204FFEC999797FD7827F7FF8E7() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TransitionResult_8EE6B66442425567E7F396BE24D553AE() end
---@param DeltaTimeX float
function USupraAnimBlueprint_C:BlueprintUpdateAnimation(DeltaTimeX) end
function USupraAnimBlueprint_C:BlueprintInitializeAnimation() end
function USupraAnimBlueprint_C:Punch() end
function USupraAnimBlueprint_C:AnimNotify_DonePunching() end
---@param Variation EShootGunAnimation::Type
---@param Alpha float
function USupraAnimBlueprint_C:Shoot(Variation, Alpha) end
USupraAnimBlueprint_C['Hold Gun'] = function(self, ) end
function USupraAnimBlueprint_C:Point() end
function USupraAnimBlueprint_C:AnimNotify_DonePointing() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TransitionResult_A6F75CC343A977E0664F9988D423B822() end
function USupraAnimBlueprint_C:Eat() end
function USupraAnimBlueprint_C:AnimNotify_DoneThreatening() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TransitionResult_F263E8084DCC5255583465840426EA36() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TransitionResult_575ADE9740BBECCD669DC4B6810854DB() end
---@param Asset UAnimSequenceBase
---@param Delay float
---@param BlendInSeconds float
---@param BlendOutSeconds float
---@param PlayRate float
---@param ForceFullBodyWhenWalking boolean
function USupraAnimBlueprint_C:EventPlayAnimation_DefaultSlot(Asset, Delay, BlendInSeconds, BlendOutSeconds, PlayRate, ForceFullBodyWhenWalking) end
function USupraAnimBlueprint_C:DebugValues() end
function USupraAnimBlueprint_C:HoldSword() end
function USupraAnimBlueprint_C:AnimNotify_FootstepLeft() end
function USupraAnimBlueprint_C:AnimNotify_FootstepRight() end
function USupraAnimBlueprint_C:AnimNotify_Land() end
function USupraAnimBlueprint_C:AnimNotify_WaterSwishForward() end
function USupraAnimBlueprint_C:AnimNotify_WaterSwishBackward() end
function USupraAnimBlueprint_C:AnimNotify_Jump() end
function USupraAnimBlueprint_C:BlueprintBeginPlay() end
function USupraAnimBlueprint_C:AnimNotify_IsNotClapping_Exited() end
function USupraAnimBlueprint_C:AnimNotify_IsNotClapping_FullyBlended() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TransitionResult_DC1BA8C64DFB0896951732845DCAE316() end
function USupraAnimBlueprint_C:AnimNotify_Clap() end
---@param Animation UAnimSequenceBase
---@param BlendInTime float
---@param BlendOutTime float
---@param PlayRate float
function USupraAnimBlueprint_C:PlayIdleAnimation(Animation, BlendInTime, BlendOutTime, PlayRate) end
function USupraAnimBlueprint_C:PlayCustomAnim() end
function USupraAnimBlueprint_C:EvaluateGraphExposedInputs_ExecuteUbergraph_SupraAnimBlueprint_AnimGraphNode_TwoWayBlend_0E57F49D4A013CB910FC2AA6A0E821AB() end
function USupraAnimBlueprint_C:DoShoot0() end
function USupraAnimBlueprint_C:DoShoot1() end
function USupraAnimBlueprint_C:Reverse() end
function USupraAnimBlueprint_C:AnimNotify_SwordSwish() end
---@param BlendOutTime float
function USupraAnimBlueprint_C:CancelIdleAnimation(BlendOutTime) end
---@param EntryPoint int32
function USupraAnimBlueprint_C:ExecuteUbergraph_SupraAnimBlueprint(EntryPoint) end


